// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGhMCB5gVvw70H12xiYoMs9B60IFwP8A',
    appId: '1:996921360023:android:a5948d9fbf8676f61bf3d2',
    messagingSenderId: '996921360023',
    projectId: 'imtihon-4oy',
    databaseURL: 'https://imtihon-4oy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'imtihon-4oy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUdNxKYNj7taEoXR0jaAPnXv9EPDuKt8',
    appId: '1:996921360023:ios:691e6ea0f446a82f1bf3d2',
    messagingSenderId: '996921360023',
    projectId: 'imtihon-4oy',
    databaseURL: 'https://imtihon-4oy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'imtihon-4oy.appspot.com',
    iosBundleId: 'com.example.shirinim',
  );
}
